version: "3.8"

services:
  torrent-aio:
    build: .
    image: torrent-aio:latest
    container_name: torrent-aio
    environment:
      - TORRENT_AIO_GROUP_NAME=${GROUP_NAME:-TORRENT-AIO}
      - TZ=${TZ:-Europe/Paris}
    volumes:
      - ./data:/data
      - ./config:/home/aio/.config
    stdin_open: true
    tty: true
    working_dir: /data
